import HashMap from "./hashMap.mjs"
import HashSet from "./hashSet.mjs"

const hmap = new HashMap()
hmap.set("Kizito", "Chima")
hmap.set("Benito", "Tochi")
hmap.set("David", "Izunna")
hmap.set("Osigwue", "Jennifer")
hmap.set("Benita", "Chidinma")
hmap.set("Christiana", "Nkechi")
hmap.set("Damian", "ikechukwu")
hmap.set("apple", "red")
hmap.set("banana", "yellow")
hmap.set("carrot", "orange")
hmap.set("dog", "brown")
hmap.set("elephant", "gray")
hmap.set("frog", "green")
hmap.set("grape", "purple")
hmap.set("hat", "black")
hmap.set("ice cream", "white")
hmap.set("jacket", "blue")
hmap.set("kite", "pink")
hmap.set("lion", "golden")
hmap.set("moon", "silver")
// hmap.remove("moon")

// console.log(hmap.remove("Osigwue"))
// console.log(hmap.remove("Benito"))
// hmap.clear()

// hmap.set("moon", "white")
console.log("Table Capacity: ", hmap.capacity)
console.log("No of Filled Buckets: ", hmap.checkNoOfFilledBuckets())
console.log("Current Load Factor: ", hmap.currentLoadFactor())
console.log("HasMap Length: ", hmap.length())
// hmap.remove("apple")
console.table(hmap.buckets)
// console.log(hmap.currentLoadFactor() >= hmap.loadFactor)
